-- =============================================================================
-- Migration 003: payment_journeys – core payment lifecycle tracking
-- =============================================================================
--
-- Each row represents a single end-to-end payment.  The journey is created
-- when the first message for a new payment is received and progresses through
-- the journey_state enum via the StateMachine.


BEGIN;

CREATE TABLE IF NOT EXISTS iso20022.payment_journeys (
    -- Stable, human-readable surrogate key generated as 'JRN-{UUIDv4}'.
    journey_id              VARCHAR(50)                     PRIMARY KEY,

    -- Current position in the payment state machine.
    current_status          iso20022.journey_state          NOT NULL,

    -- ── SWIFT gpi / ISO payment identifiers ──────────────────────────────

    -- Universal End-to-end Transaction Reference (UUIDv4 per SWIFT gpi).
    -- Generated by the engine if absent from the initiating message.
    uetr                    VARCHAR(36)                     UNIQUE,

    -- Transaction ID assigned by the instructing party (pacs.008 TxId).
    tx_id                   VARCHAR(105),

    -- End-to-end reference threaded through the entire payment chain.
    end_to_end_id           VARCHAR(35),

    -- Clearing system reference (e.g. STEP2, SWIFT reference).
    clr_sys_ref             VARCHAR(35),

    -- ── Settlement details ────────────────────────────────────────────────

    -- Interbank settlement amount with up to 5 decimal places
    -- (supports currencies like JPY with 0 decimals as well as
    --  Bahraini Dinar with 3 decimal places).
    settlement_amount       NUMERIC(20, 5),

    -- ISO 4217 three-letter currency code, e.g. 'EUR', 'USD'.
    settlement_currency     CHAR(3),

    -- Requested interbank settlement / value date.
    settlement_date         DATE,

    -- ── Agent BICs (ISO 9362 / SWIFT BIC-11) ─────────────────────────────

    instructing_agent       VARCHAR(11),
    instructed_agent        VARCHAR(11),
    debtor_agent            VARCHAR(11),
    creditor_agent          VARCHAR(11),

    -- ── Originating message reference ────────────────────────────────────

    -- Message ID of the first message that triggered this journey
    -- (typically a pain.001 or pacs.008).
    initiating_msg_id       VARCHAR(105),

    -- Message type of the initiating message, e.g. 'pain.001.001.12'.
    initiating_msg_type     VARCHAR(50),

    created_at              TIMESTAMPTZ                     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ                     NOT NULL DEFAULT NOW()
);

-- ── Lookup indexes ────────────────────────────────────────────────────────────

-- journey_id is the PK; uetr has a UNIQUE index above.
-- Additional indexes for common resolution paths used by resolve_journey_id().

CREATE INDEX IF NOT EXISTS idx_payment_journeys_tx_id
    ON iso20022.payment_journeys (tx_id)
    WHERE tx_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_journeys_end_to_end_id
    ON iso20022.payment_journeys (end_to_end_id)
    WHERE end_to_end_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_journeys_clr_sys_ref
    ON iso20022.payment_journeys (clr_sys_ref)
    WHERE clr_sys_ref IS NOT NULL;

-- Supports duplicate-payment detection query in compliance.rs.
CREATE INDEX IF NOT EXISTS idx_payment_journeys_dedup
    ON iso20022.payment_journeys (end_to_end_id, settlement_amount, settlement_currency, settlement_date)
    WHERE end_to_end_id IS NOT NULL;

-- Supports status-based operational queries.
CREATE INDEX IF NOT EXISTS idx_payment_journeys_status
    ON iso20022.payment_journeys (current_status);

DROP TRIGGER IF EXISTS trg_payment_journeys_updated_at ON iso20022.payment_journeys;
CREATE TRIGGER trg_payment_journeys_updated_at
    BEFORE UPDATE ON iso20022.payment_journeys
    FOR EACH ROW EXECUTE FUNCTION iso20022.set_updated_at();

COMMIT;
