-- =============================================================================
-- Migration 004: iso_messages – full ISO 20022 message archive
-- =============================================================================
--
-- Stores the raw XML of every message processed or generated by the engine.
-- Used for audit, replay, and journey resolution (resolve_journey_id looks
-- up journey_id via msg_id when it cannot be found on payment_journeys).


BEGIN;

CREATE TABLE IF NOT EXISTS iso20022.iso_messages (
    -- Surrogate key; the engine refers to this as 'message_internal_id'.
    message_internal_id     BIGSERIAL                       PRIMARY KEY,

    -- ISO 20022 message type, e.g. 'pacs.008.001.13'.
    msg_type                VARCHAR(50)                     NOT NULL,

    -- Whether this message was received (IN) or generated and sent (OUT).
    direction               iso20022.message_direction      NOT NULL,

    -- The MsgId value from the ISO 20022 AppHdr or document header.
    -- Used as the business-level dedup key for archive_message().
    msg_id                  VARCHAR(105)                    NOT NULL,

    -- Full XML payload as text (UTF-8).
    raw_xml                 TEXT                            NOT NULL,

    -- Journey this message belongs to; populated either at creation time
    -- (outbound) or by link_message_to_journey() after journey resolution.
    journey_id              VARCHAR(50)
                                REFERENCES iso20022.payment_journeys (journey_id)
                                ON DELETE SET NULL,

    created_at              TIMESTAMPTZ                     NOT NULL DEFAULT NOW()
);

-- archive_message() checks existence via (msg_type, direction, msg_id).
CREATE UNIQUE INDEX IF NOT EXISTS idx_iso_messages_business_key
    ON iso20022.iso_messages (msg_type, direction, msg_id);

-- resolve_journey_id() looks up journey_id by msg_id.
CREATE INDEX IF NOT EXISTS idx_iso_messages_msg_id
    ON iso20022.iso_messages (msg_id);

-- Journey-level message history.
CREATE INDEX IF NOT EXISTS idx_iso_messages_journey_id
    ON iso20022.iso_messages (journey_id)
    WHERE journey_id IS NOT NULL;

COMMIT;
