use metrics::{counter, gauge, histogram};
use metrics_exporter_prometheus::{PrometheusBuilder, PrometheusHandle};
use std::time::Instant;

// ═══════════════════════════════════════════════════════════════════════════
// Initialization
// ═══════════════════════════════════════════════════════════════════════════

/// Install the Prometheus metrics recorder and return a handle that can
/// render the `/metrics` endpoint.
///
/// Call once at startup in `main()`, before spawning any workers:
///
/// ```ignore
/// let metrics_handle = iso20022::processor::metrics::install_metrics();
/// // ... later, in your Router:
/// .route("/metrics", get(move || ready(metrics_handle.render())))
/// ```
pub fn install_metrics() -> Result<PrometheusHandle, Box<dyn std::error::Error>> {
    let handle = PrometheusBuilder::new()
        .install_recorder()?;
    Ok(handle)
}

// ═══════════════════════════════════════════════════════════════════════════
// Message Processing
// ═══════════════════════════════════════════════════════════════════════════

/// Record a fully processed inbound message.
///
/// Labels:
/// - `msg_type`: e.g. "pacs.008.001.13"
/// - `outcome`: "success" | "permanent_failure" | "transient_failure" | "rejected" | "no_handler"
pub fn record_message_processed(msg_type: &str, outcome: &str) {
    counter!("iso20022_messages_processed_total", "msg_type" => msg_type.to_string(), "outcome" => outcome.to_string())
        .increment(1);
}

/// Record processing duration for an inbound message.
pub fn record_message_duration(msg_type: &str, duration: std::time::Duration) {
    histogram!("iso20022_message_duration_seconds", "msg_type" => msg_type.to_string())
        .record(duration.as_secs_f64());
}

/// Update the current in-flight message gauge (increment on claim, decrement on complete).
pub fn set_messages_in_flight(direction: &str, count: f64) {
    gauge!("iso20022_messages_in_flight", "direction" => direction.to_string())
        .set(count);
}

/// Record a message entering the dead letter queue.
pub fn record_dead_letter(msg_type: &str) {
    counter!("iso20022_dead_letter_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Journey State Transitions
// ═══════════════════════════════════════════════════════════════════════════

/// Record a journey state transition.
pub fn record_state_transition(from_state: &str, to_state: &str, msg_type: &str) {
    counter!(
        "iso20022_journey_transitions_total",
        "from_state" => from_state.to_string(),
        "to_state" => to_state.to_string(),
        "msg_type" => msg_type.to_string()
    ).increment(1);
}

/// Record a blocked (disallowed) state transition.
pub fn record_transition_blocked(from_state: &str, attempted_state: &str, msg_type: &str) {
    counter!(
        "iso20022_journey_transitions_blocked_total",
        "from_state" => from_state.to_string(),
        "attempted_state" => attempted_state.to_string(),
        "msg_type" => msg_type.to_string()
    ).increment(1);
}

/// Record a new journey created.
pub fn record_journey_created(msg_type: &str) {
    counter!("iso20022_journeys_created_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Outbound Messages
// ═══════════════════════════════════════════════════════════════════════════

/// Record an outbound message generated by the flow coordinator.
pub fn record_outbound_generated(msg_type: &str) {
    counter!("iso20022_outbound_generated_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

/// Record an outbound message successfully sent (by notification worker).
pub fn record_outbound_sent(msg_type: &str) {
    counter!("iso20022_outbound_sent_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

/// Record an outbound send failure.
pub fn record_outbound_failed(msg_type: &str, reason: &str) {
    counter!(
        "iso20022_outbound_failed_total",
        "msg_type" => msg_type.to_string(),
        "reason" => reason.to_string()
    ).increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Compliance & Screening
// ═══════════════════════════════════════════════════════════════════════════

/// Record an AML/sanctions screening result.
pub fn record_screening_result(result: &str) {
    counter!("iso20022_screening_results_total", "result" => result.to_string())
        .increment(1);
}

/// Record a duplicate payment detection.
pub fn record_duplicate_detected() {
    counter!("iso20022_duplicate_payments_detected_total").increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Investigations & SLA
// ═══════════════════════════════════════════════════════════════════════════

/// Record a new investigation opened.
pub fn record_investigation_opened(investigation_type: &str) {
    counter!("iso20022_investigations_opened_total", "type" => investigation_type.to_string())
        .increment(1);
}

/// Record an investigation closed/resolved.
pub fn record_investigation_closed(investigation_type: &str, resolution: &str) {
    counter!(
        "iso20022_investigations_closed_total",
        "type" => investigation_type.to_string(),
        "resolution" => resolution.to_string()
    ).increment(1);
}

/// Record an SLA breach.
pub fn record_sla_breach(investigation_type: &str) {
    counter!("iso20022_sla_breaches_total", "type" => investigation_type.to_string())
        .increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Reconciliation
// ═══════════════════════════════════════════════════════════════════════════

/// Record a reconciliation result.
pub fn record_reconciliation(result: &str) {
    counter!("iso20022_reconciliation_total", "result" => result.to_string())
        .increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// CBS Booking
// ═══════════════════════════════════════════════════════════════════════════

/// Record a CBS booking attempt result.
pub fn record_cbs_booking(booking_type: &str, outcome: &str) {
    counter!(
        "iso20022_cbs_bookings_total",
        "booking_type" => booking_type.to_string(),
        "outcome" => outcome.to_string()
    ).increment(1);
}

/// Record CBS booking latency.
pub fn record_cbs_booking_duration(booking_type: &str, duration: std::time::Duration) {
    histogram!(
        "iso20022_cbs_booking_duration_seconds",
        "booking_type" => booking_type.to_string()
    ).record(duration.as_secs_f64());
}

// ═══════════════════════════════════════════════════════════════════════════
// Schema / Version
// ═══════════════════════════════════════════════════════════════════════════

/// Record a message that needed version fallback routing.
pub fn record_version_fallback(requested: &str, resolved: &str) {
    counter!(
        "iso20022_version_fallback_total",
        "requested" => requested.to_string(),
        "resolved" => resolved.to_string()
    ).increment(1);
}

/// Record an XSD validation failure.
pub fn record_validation_failure(msg_type: &str) {
    counter!("iso20022_validation_failures_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

/// Record a signature verification failure.
pub fn record_signature_failure(msg_type: &str) {
    counter!("iso20022_signature_failures_total", "msg_type" => msg_type.to_string())
        .increment(1);
}

// ═══════════════════════════════════════════════════════════════════════════
// Infrastructure
// ═══════════════════════════════════════════════════════════════════════════

/// Record a circuit breaker state change.
pub fn record_circuit_breaker_state(name: &str, state: &str) {
    gauge!(
        "iso20022_circuit_breaker_state",
        "name" => name.to_string()
    ).set(match state {
        "closed" => 0.0,
        "half_open" => 0.5,
        "open" => 1.0,
        _ => -1.0,
    });
}

/// Record maintenance loop actions.
pub fn record_maintenance_action(action: &str, count: u64) {
    counter!("iso20022_maintenance_actions_total", "action" => action.to_string())
        .increment(count);
}

/// Record DB pool checkout latency.
pub fn record_db_checkout_duration(duration: std::time::Duration) {
    histogram!("iso20022_db_checkout_duration_seconds")
        .record(duration.as_secs_f64());
}

// ═══════════════════════════════════════════════════════════════════════════
// Timer Helper
// ═══════════════════════════════════════════════════════════════════════════

/// A simple RAII timer that records duration on drop.
///
/// Usage:
/// ```ignore
/// let _timer = MetricsTimer::new("pacs.008.001.13");
/// // ... do work ...
/// // duration recorded automatically when _timer drops
/// ```
pub struct MetricsTimer {
    msg_type: String,
    start: Instant,
}

impl MetricsTimer {
    pub fn new(msg_type: &str) -> Self {
        Self { msg_type: msg_type.to_string(), start: Instant::now() }
    }
}

impl Drop for MetricsTimer {
    fn drop(&mut self) {
        record_message_duration(&self.msg_type, self.start.elapsed());
    }
}
