
pub mod messages;
pub mod handlers;
pub mod mapper;
pub mod signer;
pub mod verifier;
pub(crate) mod xml_utils;
pub mod processor;
pub mod context;
pub mod interceptor;

// Generated from `proto/crudgrpc.proto` and `proto/engine.proto` by
// `build.rs` at compile time.
//
// These used to be checked-in `src/crudgrpc.rs` / `src/engine.rs` files that
// `build.rs` did not produce and nothing regenerated, while `build.rs` still
// compiled the `.proto` files into `OUT_DIR` where no code ever read them.
// The effect was that the `.proto` files in this repo were decorative: the
// contract this service actually spoke was frozen in the checked-in Rust, and
// editing the protos changed nothing. Generating here makes the `.proto`
// files the single source of truth, so a drift against `engine`/`crudgrpc`
// shows up as a compile error rather than as a runtime failure.
#[allow(
    // Generated by prost/tonic from the .proto files - not hand-written, and
    // reformatting it to satisfy clippy would be undone by the next build.
    clippy::enum_variant_names,
    clippy::doc_markdown,
    clippy::doc_lazy_continuation,
    clippy::derive_partial_eq_without_eq,
    clippy::large_enum_variant,
)]
pub mod crudgrpc {
    tonic::include_proto!("crudgrpc");
}

#[allow(
    // Generated by prost/tonic from the .proto files - not hand-written, and
    // reformatting it to satisfy clippy would be undone by the next build.
    clippy::enum_variant_names,
    clippy::doc_markdown,
    clippy::doc_lazy_continuation,
    clippy::derive_partial_eq_without_eq,
    clippy::large_enum_variant,
)]
pub mod engine {
    tonic::include_proto!("engine");
}

#[allow(
    // Generated by prost/tonic from the .proto files - not hand-written, and
    // reformatting it to satisfy clippy would be undone by the next build.
    clippy::enum_variant_names,
    clippy::doc_markdown,
    clippy::doc_lazy_continuation,
    clippy::derive_partial_eq_without_eq,
    clippy::large_enum_variant,
)]
pub mod uidgen {
    tonic::include_proto!("uidgen");
}

pub use context::ProcessingContext;
